"""
Amang Kontol
"""
import asyncio
import random
from random import choice
from ubot import *



roast = [
    "**DAR DER DOR, GC AMPAS KU GEDOR**",
    "**MEMBER SINI PADA KEBANYAKAN NGELEM**",
    "**BUBARIN AE GC AMPAS GINI MAH ANJING**",
    "**MANA NIH MEMBERNYA, GA ADA PERGERAKAN GINI**",
    "**LU TUH GA PANTES MAEN TELE SUMPAH, MENDING LU SEKOLAH YANG BENER**",
    "**SEKOLAH MASIH DI BIAYAIN PEMERINTAH AJA BELAGU LO KONTOL**",
    "**EALAH KACUNG TELE ANAKAN SINI YA**",
    "**BWAJINGAN**",
    "**GC KAYA GINI BENERAN BIKIN ORANG MIKIR, ADA GEMBEL NYANGKUT APA?**",
    "**SIAPA YANG NARIK BENANG, JANGAN-JANGAN KARET DI CANCEL**",
    "**INFORMASI BARU: SANTET SEKARANG BISA LEWAT TELEGRAM PALING GA GUNA DI SINI**",
    "**CHAT DI GRUP INI KAYA NGOCEHAN WC UMUM, GA ADA YANG MAU DENGAR**",
    "**KALO DAPET 1 JUTA RUPAH SETIAP KALI NGETIK DI GRUP INI, LU MASIH AJA GABISA MAKIN KAYA**",
    "**BUAT NYARI ILMU DI GRUP INI KAYA CARI BUAH TANPA POKOK**",
    "**LEBIH BAIK JADI TUKANG SAPU JALAN DARIPADA JADI MEMBER GRUP INI, SETIDAKNYA DIBAYARAN**",
    "**NGOMONG-NGOMONG, APA YANG KALIAN KONTRIBUSIIN SELAIN NGELEMAK?**",
    "**KALAU PANDAI NGOMONG DOANG DAPET PIALA, LU UDAH PASTI JADI JUARA DUNIA**",
    "**KOK BISA SEKONYONG-KONYONG MASUK GC INI, LU KIRA GRUP ANTI MAINSTREAM YA?**",
    "**SARAN BESAR BUAT LU: CABUT AJA DARI GRUP INI SEBELUM OTAK LU KEJERUMUS KE LEVEL AMPASNYA**",
    "**LUCU DEH, LU NGEHINA ORANG DI GRUP INI, TAPI KALAU KELUAR JALAN MALU**",
    "**KALAU KARMA ADA DI TELEGRAM, LU UDAH PASTI JADI KORBANNYA**",
]



async def roasting_jing(client, message):
    dia = await extract_user(message)
    if dia in DEVS:
        return await message.reply("Lah si anying mo ilang akun lu ?")
    elif dia in await get_seles():
        return await message.reply("Bot lu mo ilang ?")
    else:
        await message.reply(random.choice(roast))